import Foundation

public enum SWAPISelectPerson: String {
    case luke = "people/1"
    case c3po = "people/2"
    case r2d2 = "people/3"
    case darth = "people/4"
    case leia = "people/5"
    case owen = "people/6"
    case beru = "people/7"
    case r5d4 = "people/8"
    case biggs = "people/9"
    case obiwan = "people/10"
    case anakin = "people/11"
    case twelve = "people/12"
    case thirteen = "people/13"
    case fourteen = "people/14"
    case fifteen = "people/15"
    case sixteen = "people/16"
    case seventeen = "people/17"
    case eightteen = "people/18"
    case nineteen = "people/19"
    case twenty = "people/20"
    case twentyone = "people/21"
   // case twentytwo = "people/22"
  